# The path to the directory where mitmproxy will save its media files
# Please note the path delimiter is "/" even on windows."
save_dir: "E:/Home/Documents/Programming/mitmproxy/cache/mitmproxy_media"


# Extensions that are allowed for download, will work with almost any extension
# Please realize that this is not a complete list of all possible extensions
# Also note this does not decrypt ANY data, it only collects what is passing through the proxy.
# So Encrypted video/images/audio will download but will not be readable.
# This behavior will NOT be changed.
extensions:
  - ".jpg"
  - ".jpeg"
  - ".png"
  - ".gif"
  - ".webp"
  - ".mp4"
  - ".webm"
  - ".mov"


# IF enabled then only allow downloads from patterns matching these regex expressions
# whitelist:
#   - "cdn\\..*"
#   - "images\\.amazonaws\\.com"


# Block downloads from patterns matching these regex expressions
# Good place to put advertizing networks
blacklist:
  - "ads\\..*"
  - ".*\\.doubleclick\\.net"


# Filter out images with dimensions outside of these thresholds
filter_pixel_dimensions:
  enabled: true         # Turn on to activate filtering
  min_width: 301        # Try to filter out small images like thumbnails/icons, etc.
  min_height: 301       # Try to filter out small images like thumbnails/icons, etc.
  max_width: 12000      # Super High Resolution
  max_height: 12000     # Super High Resolution


# Filter out files that are too large or small
filter_file_size:
  enabled: true
  min_bytes: 10240         # 10 KB
  max_bytes: 157286400     # 150 MB Increase if you want video or large files


# Logs and various other settings
log_seen_domains: true       # Save new domains to domains_seen.txt
auto_reload_config: true     # Reload YAML config on change
