firefox: E:/Home/PortableApps/PortableApps/FirefoxPortable/App/Firefox64/firefox.exe
firefoxportable: E:/Home/PortableApps/PortableApps/FirefoxPortable/FirefoxPortable.exe
googlechromeportable: E:/Home/PortableApps/PortableApps/GoogleChromePortable64/GoogleChromePortable.exe
