brave: C:/portapps/brave-portable/app/brave.exe
chrome: E:/Home/PortableApps/PortableApps/GoogleChromePortable64/App/Chrome-bin/chrome.exe
firefox: E:/Home/PortableApps/PortableApps/FirefoxPortable/App/Firefox64/firefox.exe
opera: E:/Home/PortableApps/PortableApps/OperaPortable/App/Opera/opera.exe
