kmeleon: E:\Home\PortableApps\PortableApps\K-MeleonPortable\App\K-Meleon\k-meleon.exe
librewolf: E:\Home\PortableApps\PortableApps\LibreWolfPortable\App\LibreWolf\librewolf.exe
links: E:\Home\PortableApps\PortableApps\LinksPortable\App\links\links-g.exe
seamonkey: E:\Home\PortableApps\PortableApps\SeaMonkeyPortable\App\SeaMonkey64\seamonkey.exe
vivaldi: C:\portapps\vivaldi-standalone\Application\vivaldi.exe
