chrome: "C:/Program Files/Google/Chrome/Application/chrome.exe"
firefox: "C:/Program Files/Mozilla Firefox/firefox.exe"
brave: "C:/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe"
safari: "/Applications/Safari.app"
