save_dir: E:\Home\Documents\Programming\tzMCP\cache
allowed_mime_groups:
- image
whitelist: []
blacklist:
- doubleclick.net
- lastpass.com
filter_pixel_dimensions:
  enabled: true
  min_width: 301
  min_height: 301
  max_width: 12000
  max_height: 12000
filter_file_size:
  enabled: true
  min_bytes: 5000
  max_bytes: 157286400
log_internal_debug: true
log_seen_domains: true
auto_reload_config: true
